### ISSUE TITLE
security

### ISSUE THREAD

**Issue by fedorchuck** [fedorchuck/web-store#6]
add Spring Security for logging/authorize

**Comment by fedorchuck** [comment]
fixed by https://github.com/fedorchuck/web-store/commit/9811e95e1b4c7c7608d9289eeac4c6fd2c3221b0 (session)

**Comment by Mart-Bogdan** [comment]
В каком месте это Spring Security?
 https://habrahabr.ru/post/203318/ http://devcolibri.com/3810

Это "хак" с сессионными переменными

**Comment by fedorchuck** [comment]
https://github.com/fedorchuck/web-store/issues/10
https://github.com/fedorchuck/web-store/issues/11
